#!/bin/bash -e

CONF_FILE=$ZOOKEEPER_HOME/conf/zoo.cfg

if [ ! -f $CONF_FILE ]; then
    echo "tickTime=2000" >> $CONF_FILE
    echo "dataDir=$ZOOKEEPER_HOME/data" >> $CONF_FILE
    echo "clientPort=2181" >> $CONF_FILE
fi

$ZOOKEEPER_HOME/bin/zkServer.sh start-foreground
